# version: "3.5"
services:
    app:
        build:
            context: .
        container_name: student-backend-3
        ports:
            - "3000:8080"

        depends_on:
            - db

        environment:
            - DATABASE_URL=postgres://postgres:123@db:5432/StudentDB
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules

    db:
        image: postgres
        container_name: student-backend-db
        ports:
            - "3001:5432"
        environment:
            - POSTGRES_PASSWORD= 123
            - POSTGRES_DB= StudentDB
            - POSTGRES_USER=postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
